#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -std=c++11 -D_REENTRANT
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"."
CCC           = $(CXX)
MAKEFILE      = Makefile.tree
DEPENDENCIES  = .depend.$(MAKEFILE)
BTARGETDIR    = ./
BIN           = $(BTARGETDIR)tree$(EXESUFFIX)$(EXEEXT)
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -O
LDLIBS        = -ldl $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so))))) -lpthread
OBJS          = Add_Expr_Node$(OBJEXT) Binary_Expr_Node$(OBJEXT) Calculator_Node_Factory$(OBJEXT) Calculator$(OBJEXT) Close_Parentheses_Node$(OBJEXT) Divide_Expr_Node$(OBJEXT) driver$(OBJEXT) Eval_Expr_Tree_Visitor$(OBJEXT) Expr_Tree_Builder$(OBJEXT) Modulus_Expr_Node$(OBJEXT) Multiply_Expr_Node$(OBJEXT) Num_Expr_Node$(OBJEXT) Open_Parentheses_Node$(OBJEXT) Subtract_Expr_Node$(OBJEXT) Unary_Expr_Node$(OBJEXT)
SRC           = Add_Expr_Node.cpp Binary_Expr_Node.cpp Calculator_Node_Factory.cpp Calculator.cpp Close_Parentheses_Node.cpp Divide_Expr_Node.cpp driver.cpp Eval_Expr_Tree_Visitor.cpp Expr_Tree_Builder.cpp Modulus_Expr_Node.cpp Multiply_Expr_Node.cpp Num_Expr_Node.cpp Open_Parentheses_Node.cpp Subtract_Expr_Node.cpp Unary_Expr_Node.cpp
LINK.cc       = $(LD) $(LDFLAGS)
EXPORTFLAGS   = 
DEPLIBS       = $(foreach lib, , $(foreach libpath, ., $(wildcard $(libpath)/lib$(lib).a)))

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(BIN)

$(BIN): $(OBJS) $(DEPLIBS)
	@$(TESTDIRSTART) "$(BTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(BTARGETDIR)"
	$(LINK.cc) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

generated: $(GENERATED_DIRTY)
	@-:

Add_Expr_Node$(OBJEXT): Add_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Add_Expr_Node.cpp

Binary_Expr_Node$(OBJEXT): Binary_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Binary_Expr_Node.cpp

Calculator_Node_Factory$(OBJEXT): Calculator_Node_Factory.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Calculator_Node_Factory.cpp

Calculator$(OBJEXT): Calculator.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Calculator.cpp

Close_Parentheses_Node$(OBJEXT): Close_Parentheses_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Close_Parentheses_Node.cpp

Divide_Expr_Node$(OBJEXT): Divide_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Divide_Expr_Node.cpp

driver$(OBJEXT): driver.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) driver.cpp

Eval_Expr_Tree_Visitor$(OBJEXT): Eval_Expr_Tree_Visitor.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Eval_Expr_Tree_Visitor.cpp

Expr_Tree_Builder$(OBJEXT): Expr_Tree_Builder.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Expr_Tree_Builder.cpp

Modulus_Expr_Node$(OBJEXT): Modulus_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Modulus_Expr_Node.cpp

Multiply_Expr_Node$(OBJEXT): Multiply_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Multiply_Expr_Node.cpp

Num_Expr_Node$(OBJEXT): Num_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Num_Expr_Node.cpp

Open_Parentheses_Node$(OBJEXT): Open_Parentheses_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Open_Parentheses_Node.cpp

Subtract_Expr_Node$(OBJEXT): Subtract_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Subtract_Expr_Node.cpp

Unary_Expr_Node$(OBJEXT): Unary_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Unary_Expr_Node.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(BIN)

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) -Wall -Wextra -pedantic -fsyntax-only $(CHK_SOURCES)

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------


depend:
	-$(MPC_ROOT)/depgen.pl  $(CFLAGS) $(CCFLAGS) $(CPPFLAGS) -f $(DEPENDENCIES) $(SRC) 2> $(NUL)

-include $(DEPENDENCIES)
